<table class="table">
    <thead>
        <tr>
            <th>Guest</th>
            <th>Year</th>
            <th>Cell</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Mark</td>
            <td>Sophomore</td>
            <td>516</td>
        </tr>
        <tr>
            <td>Bryk</td>
            <td>Junior</td>
            <td>516</td>
        </tr>
    </tbody>
</table>